env:
  es6: true
  browser: true
  commonjs: true

extends: ['airbnb', 'airbnb/hooks', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'

rules: {
  "react/jsx-filename-extension": [0],
  "import/no-named-as-default": 0,
  "react/jsx-fragments": [<enabled>, <mode>]
}
